### PR TITLE
D4map fix v1

### PR DESCRIPTION
**Pull request by jgallagher59701**
This is my first try at fixing the D4Map deep copy debacle. This is not yet been verified by running it against the BES, but it does pass the libdap tests.

### CODE REVIEW

**Comment by jgallagher59701** [comment]
This PR does result in a BES that passes it's tests and does also pass the ObjMemCache issue by-hand test.
I'm not sure how to formally test the problem, however. Maybe Kent's ticket to test the ObjMemCache will help.
Should this me merged?

**Review by kyang2014 — COMMENTED** [review]
James, you need to add a BES object memory test to the testsuite at the netCDF-handler by following your hand test.  Basically add  another -i foo.bescmd of your normal besstandalone like this:
`besstandalone -c tests/bes.conf -i foo.bescmd -i foo.bescmd`

**Comment by jgallagher59701** [comment]
Yo, I can add a test to the BES, but we won't see if that works until this is merged. However, I could write a unit test, verify that it fails without this change and that is passes with the change.

**Review by kyang2014 — APPROVED** [review]
I tested the HDF5 handler's memory cache tests with this branch. It passed all the tests. I also manually tested the netCDF handler with the test Nathan reported. It also passes the test. So your change works fine.  There are some code smells reported in the sonar cloud. You may need to take a look and see if some code smells need to be removed.

**Pull request merged**
