### PR TITLE
Fix Constructor::read()

### PR DESCRIPTION
**Pull request by jgallagher59701**
This is a candidate fix for HYRAX-702 - hard to test with unit or integration tests. I want to see if it passes on Linux.
The BES builds and passes all its tests with this change on OSX.

### CODE REVIEW

**Review by ndp-opendap — COMMENTED** [review]
That's not much of a change - Did you commit everything?

**Comment by jgallagher59701** [comment]
Yes. It’s a small change to one method, essentially.

—
James Gallagher
***@***.***

**Comment by ndp-opendap** [comment]
> Yes. It’s a small change to one method, essentially. — James Gallagher ***@***.***
> […](#)

But the only changes I see are comments. One added and one removed.

Is that right?

**Comment by jgallagher59701** [comment]
Please review

**Pull request merged**
