### PR TITLE
Xsputn

### PR DESCRIPTION
**Pull request by travis-ci-opendap**
Fixing the >2GB variable problem in libdap4 data transmission.

### CODE REVIEW

**Review by jgallagher59701 — APPROVED** [review]
This looks good.

**Comment by jgallagher59701** [comment]
@ndp-opendap Can/should we merge this?

**Review by jgallagher59701 — APPROVED** [review]
:shipit: 

Thanks!

**Comment by jgallagher59701** [comment]
@ndp-opendap Do you want to merge this or should I?

**Review by ndp-opendap — CHANGES_REQUESTED** [review]
We need to discuss this.

**Comment by jgallagher59701** [comment]
I think we should merge this and get the pre-commit working.
There are some more improvements, but cycling on this branch is tedious and the code here works.

**Pull request merged**
